
% Plotting Number of Bubbles for each methods comparing to Ground Truth
setup

% ground truth no of bubble video 2 (this was done manually)
noBubGT2 = [0, 0, 1, 1, 1, 1, 0, 0,... 
           0, 0, 2, 4, 6, 6, 5, 5,... 
           4, 3, 3, 5, 6, 6, 6, 6,... 
           6, 6, 6, 5, 6, 6, 6, 6,...
           6, 6, 6, 6, 6, 6, 6, 6,... 
           6, 6, 6, 6, 6, 6, 6, 6,... 
           6, 6, 5, 5, 3, 3, 3 ,3,... 
           4, 5, 5, 5, 5, 4, 4, 4 ];
       
       
% set up x axis (frame number)
x = zeros(size(noBubGT2));
k = 1;
for i = 1:2:128
    x(k) = i;
    k = k+1;
end

% plotting (need to run all methods to get results first)
figure(1);
plot(x, noBubGT2, 'k',...
    x, noBubArray_HERB, '--y',...
    x, noBubArray_HERRM, '--m',...
    x, noBubArray_STM,'--c',...
    x, noBubArray_STMRB, '--r',...
    x, noBubArray_STMRRM, '--g',...
    x, noBubArray_RemBaseVid, '--b');


% labeling
title('Number of Bubbles obtained after applying MSER from each pre-processing methods');
ylabel('Number of bubbles');
xlabel('Frame number');
legend('Ground Truth',...
    'Histogram Equalisation + Remove Background',...
    'Histogram Equalisation + Remove Reverse Median',...
    'Mean Shift',...
    'Mean Shift + Remove Background',...
    'Mean Shift + Remove Reverse Median',...
    'Remove Base Video');



